### ISSUE TITLE
cannot run HPVCreator on OSX 10.12

### ISSUE THREAD

**Issue by ascorbin** [HasseltVR/Holo_Toolset#3]
Hi

Hm, sadly HPVCreator 1.1 can't be opened on OS X 10.12

greetings

**Comment by HasseltVR** [comment]
hi @ascorbin , 

I'll see if I can get hold on a Mac OS Sierra machine to compile the application on. 

Best

**Comment by HasseltVR** [comment]
hi @ascorbin , 

I've uploaded a new Mac app bundle (still on release 1.1) that I compiled on 10.12. Should work until 10.9. Can you test?

[Updated release v.1.1](https://github.com/HasseltVR/Holo_Toolset/releases/tag/v1.1)

Thanks

**Comment by ascorbin** [comment]
Hi,

Hm, sadly its already not working. It just says "can't be opened" without further information.

greetings

(windows 10 version is fine)

**Comment by HasseltVR** [comment]
Hello @ascorbin ,

thanks for testing. Might be a permission issue that occurs while unzipping the app bundle, since I use the official Qt deployment tool for Mac OS X.

Can you check the following from a terminal:
```
cd HPVCreator.app/Contents/MacOS/
ls -l
```

-> check if user/all have execute permissions (denoted by the x that should at least occur in the first triplet of characters after -)
`-rwxr-xr-x  1 vjacobs  staff  413776 Apr 30 14:55 HPVCreator`


If not: `cd ..` back to directory where app bundle resides and do:

`chmod a+x /HPVCreator.app/Contents/MacOS/*`

The app should now open by double clicking the app bundle. 

If this still doesn't work, also try starting the app from terminal and let me know if any errors are reported:
```
cd HPVCreator.app/Contents/MacOS/
./HPVCreator
```

**Comment by ascorbin** [comment]
Hi HasseltVR

Yes! you are right. works.

greetings

**Comment by HasseltVR** [comment]
Great, thanks for replying. 

Added this info to release.

**Comment by ascorbin** [comment]
thanks for your awesome library!

greetings
